module.exports = {
  mode: 'jit',
  content: [
    './pages/**/*.{js,ts,jsx,tsx}',
    './components/**/*.{js,ts,jsx,tsx}',
    './node_modules/flowbite/**/*.js',
  ],
  theme: {
    extend: {
      colors: {
        Blue: '#006ba6',
        Pink1: '#EB4A4E',
        Pink2: '#EF666A',
        Pink3: '#F08386',
        Beige1: '#F4CAC4',
        Beige2: '#F3ECD0',
        Cyan: '#17A398',
        Cyan2: '#1CB9AD',
        Cyan3: '#1FCFC1',
        Purple: '#662C91',
        Purple2: '#7B35AF',
        Purple3: '#9047C6',
        Black: '#33312E',
        Black2: '#44423E',
        Black3: '#5C5854',
        Yellow: '#FFD028',
        Yellow2: '#FFD954',
        Yellow3: '#FFE070',
        Orange: '#FAA612',
        Orange2: '#FAB63D',
        Orange3: '#FCC569',
      },
    },
    fontFamily: {
      sans: ['Rubik', 'sans-serif'],
      heading: ['Rubik', 'sans-serif'],
    },
  },
  plugins: [require('flowbite/plugin')],
};
